[package]
name = "frame_locker"
version = "0.1.0"
authors = ["Endre Erős <endree@chalmers.se>"]
edition = "2021"
autotests = false

[dependencies]
r2r = "0.6.2"
futures = "0.3.15"
tokio = { version = "1", features = ["full"] }
serde = "1.0.136"
serde_json = "1.0.79"
